In [1]:
### Operadores Aritmeticos ###


#Operasiones con enteros
print(3+4)
print(3-4)
print(3*4)
print(3/4)
print(10%3)
print(10//3)
print(2**3)
print(2**3+3-7/1//4)

#operasiones con cadenas de texto
print("Hola "+"Python"+"¿Que tal?")
print("Hola "+str(5))

# Operasiones mixtas
print("Hola"*5)
print("Hola "*(2**3))

my_float=2.5 * 2
print("Hola " * int(my_float))

###Operasiones comparativos###

#Operasiones con enteros
print(3 > 4)
print(3 < 4)
print(3 >= 4)
print(4 <= 4)
print(3 == 4)
print(3 != 4)

#Operasiones con cadenas de texto

7
-1
12
0.75
1
3
8
10.0
Hola Python¿Que tal?
Hola 5
HolaHolaHolaHolaHola
Hola Hola Hola Hola Hola Hola Hola Hola

NameError: name 'my' is not defined